import './globals.scss'
import { NavBar } from '@/app/common/nav-bar';
import styles from '@/app/page.module.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    </head>
      <body>
      <NavBar></NavBar>
      <main className={styles.main}>
          {children}
      </main>
      <footer className={styles.footer}>
        Next.js @Ausy Technologies Germany 2023
      </footer>
      </body>
    </html>
  )
}
